// Demo subscription plans for TechGila
// These are fallback plans when API doesn't return any

import type { SubscriptionPlan } from "./api";

export const DEMO_SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 1,
    name: "Starter BuildIQ",
    slug: "starter-buildiq",
    description:
      "Perfect for small teams getting started with AI-powered builds",
    price: "29.00",
    currency: "USD",
    interval: "month",
    trial_days: 0,
    features: [
      "Up to 5 team members",
      "1,000 builds/month",
      "Basic queue intelligence",
      "GitHub integration",
      "Email support",
    ],
    is_active: true,
  },
  {
    id: 2,
    name: "Pro TestFlow",
    slug: "pro-testflow",
    description: "For growing teams who need advanced AI testing features",
    price: "99.00",
    currency: "USD",
    interval: "month",
    trial_days: 0,
    features: [
      "Up to 25 team members",
      "10,000 builds/month",
      "Advanced AI prioritization",
      "Predictive failure detection",
      "All CI/CD integrations",
      "Real-time dashboard",
      "Priority support",
    ],
    is_active: true,
  },
  {
    id: 3,
    name: "Enterprise PipelineAI",
    slug: "enterprise-pipelineai",
    description: "Full power for large organizations with complex pipelines",
    price: "499.00",
    currency: "USD",
    interval: "month",
    trial_days: 0,
    features: [
      "Unlimited team members",
      "Unlimited builds",
      "Custom AI models",
      "Advanced analytics",
      "SSO & SAML",
      "Dedicated account manager",
      "24/7 phone support",
      "SLA guarantee",
    ],
    is_active: true,
  },
  {
    id: 4,
    name: "Starter BuildIQ Annual",
    slug: "starter-buildiq-annual",
    description:
      "Perfect for small teams getting started with AI-powered builds",
    price: "296.00",
    currency: "USD",
    interval: "year",
    trial_days: 0,
    features: [
      "Up to 5 team members",
      "1,000 builds/month",
      "Basic queue intelligence",
      "GitHub integration",
      "Email support",
    ],
    is_active: true,
  },
  {
    id: 5,
    name: "Pro TestFlow Annual",
    slug: "pro-testflow-annual",
    description: "For growing teams who need advanced AI testing features",
    price: "1010.00",
    currency: "USD",
    interval: "year",
    trial_days: 0,
    features: [
      "Up to 25 team members",
      "10,000 builds/month",
      "Advanced AI prioritization",
      "Predictive failure detection",
      "All CI/CD integrations",
      "Real-time dashboard",
      "Priority support",
    ],
    is_active: true,
  },
  {
    id: 6,
    name: "Enterprise PipelineAI Annual",
    slug: "enterprise-pipelineai-annual",
    description: "Full power for large organizations with complex pipelines",
    price: "5090.00",
    currency: "USD",
    interval: "year",
    trial_days: 0,
    features: [
      "Unlimited team members",
      "Unlimited builds",
      "Custom AI models",
      "Advanced analytics",
      "SSO & SAML",
      "Dedicated account manager",
      "24/7 phone support",
      "SLA guarantee",
    ],
    is_active: true,
  },
];

export const DEFAULT_PLAN_SLUG = "starter-buildiq";
